version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9,21 * * *"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/plugins/memory-tencentdb"
    schedule:
      interval: "cron"
      cronjob: "10 9,21 * * *"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/plugins/yuanbao"
    schedule:
      interval: "cron"
      cronjob: "20 9,21 * * *"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/plugins/openclaw-weixin"
    schedule:
      interval: "cron"
      cronjob: "30 9,21 * * *"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/plugins/lightclawbot"
    schedule:
      interval: "cron"
      cronjob: "40 9,21 * * *"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
